version: "3.8"

services: 
  api:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports: 
      - 8080:8080
    volumes: 
      - ./backend:/api
      - '/api/node_modules'
    depends_on: 
      - mysql_server

  mysql_server:
    image: mysql:8.0
    environment: 
      - MYSQL_USER=mina
      - MYSQL_DB=testapp
      - MYSQL_PASSWORD=Crestlove_13
      - MYSQL_ROOT_PASSWORD=myRoot

 