version: "3.8"
services: 
  api:
    container_name: nodeappcontainer
    image: nodeapp:v1
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports: 
      - 8082:8082
    expose:
      - 8082
    networks:
      - internalnet
    volumes: 
      - ./backend:/api
      - '/api/node_modules'
    depends_on: 
      - mysqldb
    environment:
      - HOST=localhost
      - REACT_APP_HOST=localhost
      - REACT_APP_SERVER_PORT=8082
      - REACT_PORT=3000
      - NODE_ENV=development

  mysqldb:
    image: mysql:8.0
    container_name: mysqlcontainer
    restart: unless-stopped
    volumes:
      - ./sql/mysql.sql:/docker-entrypoint-initdb.d/0_init.sql
      - ~/DEVELOPMENT_CODE/Sql:/var/lib/mysql
    ports:
      - 3307:3306
    expose:
      - 3306
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_DATABASE=reactapp
      - MYSQL_USER=mina
      - MYSQL_PASSWORD=Crestlove_13
      - MYSQL_ROOT_PASSWORD=myRoot
      - SERVICE_TAGS=dev
      - SERVICE_NAME=mysqldb
      - NODE_ENV=development
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge