version: "3.8"

services: 
  api:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports: 
      - 8082:8082
    volumes: 
      - ./backend:/api
      - '/api/node_modules'
    depends_on: 
      - mysql_server

  mysql_server:
    image: mysql:8.0
    environment: 
      - MYSQL_HOST=localhost
      - MYSQL_USER=mina
      - MYSQL_DATABASE=reactapp
      - MYSQL_PASSWORD=Crestlove_13
      - MYSQL_PORT=3306s

 